### PR TITLE
WIP: PHPStan 0.12 support

### PR DESCRIPTION
**Pull request by gulien**
Hello @pepakriz 

Thank you for those rules 👍 

This PR is an attempt to bring PHPStan 0.12 support. Not sure it will be enough though 🤔

### CODE REVIEW

**Comment by pepakriz** [comment]
Hi, thank you!

You must do the same in `require-dev` section. CI pipeline is green because it's not tested against 0.12.x

**Comment by pepakriz** [comment]
@gulien Do you know you can run checks locally? `composer run check`

**Comment by gulien** [comment]
Yes sorry for the spam!

FYI, I'm running the `check` script inside a Docker container:

```
 docker run --rm -ti -v "$PWD:/usr/src/app" thecodingmachine/php:7.4-v3-cli bash
```

The script `check` fails at `check:cs` with a bunch of the following errors:

```
FILE: /usr/src/app/tests/src/Rules/UselessThrowsPhpDocRuleTest.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 8 | ERROR | Class name
   |       | Pepakriz\PHPStanExceptionRules\Rules\UselessThrowsPhpDocRuleTest
   |       | does not match filepath
   |       | /usr/src/app/tests/src/Rules/UselessThrowsPhpDocRuleTest.php.
   |       | (SlevomatCodingStandard.Files.TypeNameMatchesFileName.NoMatchBetweenTypeNameAndFileName)
----------------------------------------------------------------------
```

Anyway, I've focused on the two following scripts: `check:types` (now = `phpstan analyse --level=8 src tests`) and `check:tests`.

For the first one (`check:types`), I get a bunch of weird errors:

```
 ------ -------------------------------------------------------------------- 
  Line   src/Rules/ThrowsPhpDocInheritanceRule.php                           
 ------ -------------------------------------------------------------------- 
         Internal error: array_keys() expects parameter 1 to be array, null  
         given                                                               
         Run PHPStan with --debug option and post the stack trace to:        
         https://github.com/phpstan/phpstan/issues/new                       
 ------ -------------------------------------------------------------------- 
```

??? 🤔 

For the tests, I've fixed the errors but a lof of them are failing 😄and as I've never developed a PHPStan extension I am a bit lost to be fair...

**Comment by pepakriz** [comment]
Yeah, It'll be a little bit difficult. And we need to drop support for 0.11.x, because there'll be a lot of BC changes...

**Comment by pepakriz** [comment]
@gulien check my alternative PR: https://github.com/pepakriz/phpstan-exception-rules/pull/111

**Comment by pepakriz** [comment]
@gulien also released https://github.com/pepakriz/phpstan-exception-rules/releases/tag/v0.10.0

**Pull request closed without merging**
