### PR TITLE
Add Expr Throw - PHP 8

### PR DESCRIPTION
**Pull request by janatjak**
Add support for PHP 8 [Throw Expression](https://wiki.php.net/rfc/throw_expression)

Example:
```php
$value = $nullableValue ?? throw new InvalidArgumentException();
```

### CODE REVIEW

**Comment by pepakriz** [comment]
@janatjak Thank you. Can you include/improve tests to cover this case?

If I see correctly, this PR resolves https://github.com/pepakriz/phpstan-exception-rules/issues/145

**Comment by janatjak** [comment]
@pepakriz

yes, this PR should resolves expression problems
tests added

**Comment by janatjak** [comment]
@pepakriz i fixed lint error with [matrix.php-version == '8.0'](https://github.com/pepakriz/phpstan-exception-rules/pull/146/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR46)

is it ok or do you have another suggestion how to solve this issue?

**Comment by pepakriz** [comment]
@janatjak I think CI is failing because the project depends on a very old version of php_codesniffer.

**Comment by pepakriz** [comment]
@janatjak I'm taking it back. Your solution is OK

**Comment by janatjak** [comment]
> @janatjak I'm taking it back. Your solution is OK

thanks, btw phpstan fixed

**Pull request merged**
