### PR TITLE
Report useless throws annotations (fixed #32)

### LINKED ISSUE #32: Useless throws annotation not detected for children
Following code could be checked for useless throws annotation (`NotFoundException` extends `HttpException`).

```php
/**
 * @throws HttpException
 * @throws NotFoundException
 */
```

What do you think?

### PR DESCRIPTION
**Pull request by pepakriz**

### CODE REVIEW

**Comment by marcospassos** [comment]
I'll review it until tomorrow ;)

**Comment by marcospassos** [comment]
#71 will have an impact on this. 

I'd recommend we holding it until I fix it, is it OK for you?

**Comment by pepakriz** [comment]
@marcospassos rebased on current master

**Comment by marcospassos** [comment]
I've started reviewing it.

**Comment by marcospassos** [comment]
@pepakriz I committed a fix to ensure the order of the annotations won't affect the result. I also changed some methods to rely on the broker instead of native reflection.

**Comment by marcospassos** [comment]
I do not see any other major issues.

**Review by marcospassos — APPROVED** [review]
I do not see any other issues.

**Comment by pepakriz** [comment]
Nice, thank you!

**Pull request merged**
