### PR TITLE
Support for PHPStan 1.0

### PR DESCRIPTION
**Pull request by rmikalkenas**
Suggestion would be to also tag as 1.0 as all the others custom rules libraries do it

### CODE REVIEW

**Comment by pepakriz** [comment]
@rmikalkenas please change `branch-alias` in composer.json to `0.12-dev` and I'll merge it. I think it'll be better to release it as 0.12 instead of 1.0, because this project is near the end of its journey. Everybody should switch to phpstan core.

Thank you

**Comment by rmikalkenas** [comment]
Hei @pepakriz thanks for helping! Was quite busy with other work

Probably I will start a migration to native phpstan exception rules, somehow thought that it doesnt have one..

**Comment by jakzal** [comment]
@rmikalkenas @pepakriz thanks for this fix.

@pepakriz when are you planning to make a new release?

**Comment by pepakriz** [comment]
@jakzal Probably right now

**Pull request merged**
