### PR TITLE
Div returns only DivisionByZeroError

### LINKED ISSUE #136: Native division does not throw ArithemticError
In #77 checks for ArithmeticError were added, however I don't think that native division (eg. `$x / $y`) can actually throw this. https://github.com/pepakriz/phpstan-exception-rules/issues/77#issuecomment-477955886 mentions only two ways to get the error:

> 1.    intdiv(PHP_INT_MIN, -1);
> 2.    1 << -3;

And the [PHP docs for ArithmeticError](https://www.php.net/manual/en/class.arithmeticerror.php) don't mention anything about native division.

If it's not possible for it to be thrown here, maybe we shouldn't be reporting it as an issue?

### PR DESCRIPTION
**Pull request by VincentLanglet**
Close #136

### CODE REVIEW

**Review by pepakriz — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Any idea why
```
new ReflectionClass(rand(0, 1) === 0 ? static::class : Throwable::class);
```
is now throwing an exception @pepakriz ?

**Comment by VincentLanglet** [comment]
Turns out that the tests are working with phpstan 0.12.54 but not anymore since phpstan 0.12.55

Maybe you can help me on this @ondrejmirtes ? Why the two following lines have a different behaviour
```
		new ReflectionClass(rand(0, 1) === 0 ? self::class : Throwable::class);
		new ReflectionClass(rand(0, 1) === 0 ? static::class : Throwable::class);
```

The code used is 
```
	private function resolveReflectionClass(New_ $newNode, Scope $scope): Type
	{
		$reflectionExceptionType = new ObjectType(ReflectionException::class);
		if (!isset($newNode->args[0])) {
			return $reflectionExceptionType;
		}

		$valueType = $this->resolveType($newNode->args[0]->value, $scope);
		foreach (TypeUtils::getConstantStrings($valueType) as $constantString) {
			if (!$this->broker->hasClass($constantString->getValue())) {
				return $reflectionExceptionType;
			}

			$valueType = TypeCombinator::remove($valueType, $constantString);
		}

		if (!$valueType instanceof NeverType) {
			return $reflectionExceptionType;
		}

		return new VoidType();
	}
```

**Comment by VincentLanglet** [comment]
Seems like `TypeUtils::getConstantStrings` returns 
```
array(2) {
  [0]=>
  object(PHPStan\Type\Constant\ConstantStringType)#24947 (2) {
    ["value":"PHPStan\Type\Constant\ConstantStringType":private]=>
    string(65) "Pepakriz\PHPStanExceptionRules\Rules\PhpInternalFunctions\Example"
    ["isClassString":"PHPStan\Type\Constant\ConstantStringType":private]=>
    bool(true)
  }
  [1]=>
  object(PHPStan\Type\Constant\ConstantStringType)#24958 (2) {
    ["value":"PHPStan\Type\Constant\ConstantStringType":private]=>
    string(9) "Throwable"
    ["isClassString":"PHPStan\Type\Constant\ConstantStringType":private]=>
    bool(true)
  }
}
```
for `new ReflectionClass(rand(0, 1) === 0 ? self::class : Throwable::class);` but an empty array for `static::class`.

**Comment by VincentLanglet** [comment]
Created https://github.com/phpstan/phpstan/issues/4233

**Pull request merged**
